# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5b7b61b3cd335a062be79a8cf6a418540911fd1d4e7cc777a86b1ce6bf9ff885ea1ca23e753f284a9c675384a6ccef9e7bde1f1207671a4a8e1d6b5df83154e

test:
  secret_key_base: e17a4bd31908b6994abd785fa719de3c2557864fcb18678aafc59d336a0c374b56dbc8ac7e645d33416907d08c48951180abdabaa795356c1d1e920482da3d48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
